services:
  hikvision-nvr:
    build: .
    image: hikvision-nvr:gateway
    container_name: hikvision-nvr
    environment:
      API_KEY: "d383c4260a5786aafc4756d5b922e34cb153d4e1bf9b58c9e51159f41ef59958"
    volumes:
      - hikvision-data:/app/data
    ports:
      - "8001:8000"
    restart: unless-stopped

volumes:
  hikvision-data:
